name: my_flutter_game
description: >
  A simple cross-platform Flutter game template for Android and iOS.
  （シンプルなクロスプラットフォームFlutterゲームのテンプレート）

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.15.0
  audioplayers: ^5.2.0
  google_mobile_ads: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/sounds/
