name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-aab:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Ensure Android SDK packages (API 35)
        run: |
          if [ -n "$ANDROID_HOME" ] && [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
            "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
              "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          else
            echo "sdkmanager not found; relying on default image SDK"
          fi

      - name: Sanity check app icons
        run: |
          ls -l android/app/src/main/res/mipmap-*/ic_launcher.png || true
          file android/app/src/main/res/mipmap-*/ic_launcher.png || true

      - name: Prepare Android keystore
        if: ${{ secrets.ANDROID_KEYSTORE && secrets.ANDROID_STORE_PASSWORD && secrets.ANDROID_KEY_ALIAS && secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "Decoding keystore"
          mkdir -p android
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/keystore.jks
          cat > android/key.properties << 'EOF'
          storePassword=${ANDROID_STORE_PASSWORD}
          keyPassword=${ANDROID_KEY_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          storeFile=keystore.jks
          EOF
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Accept Android licenses (best-effort)
        run: |
          if [ -n "$ANDROID_HOME" ] && [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          else
            echo "sdkmanager not found; skipping license acceptance"
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test -r expanded

      - name: Build Android App Bundle (release)
        run: flutter build appbundle --release

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
