name: Android Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-aab:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Prepare Android keystore
        if: ${{ secrets.ANDROID_KEYSTORE && secrets.ANDROID_STORE_PASSWORD && secrets.ANDROID_KEY_ALIAS && secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "Decoding keystore"
          mkdir -p android
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/keystore.jks
          cat > android/key.properties << 'EOF'
          storePassword=${ANDROID_STORE_PASSWORD}
          keyPassword=${ANDROID_KEY_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          storeFile=keystore.jks
          EOF
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Accept Android licenses (best-effort)
        run: |
          if [ -n "$ANDROID_HOME" ] && [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          else
            echo "sdkmanager not found; skipping license acceptance"
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test -r expanded

      - name: Build Android App Bundle (release)
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

