name: Build and Deploy to Google Play

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Clean build directory
      run: flutter clean && flutter pub get

    - name: Generate Upload Keystore
      run: |
        keytool -genkey -v -keystore android/app/keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 -alias upload \
          -storepass android123 -keypass android123 \
          -dname "CN=Katoryo Games, OU=Development, O=Katoryo Games, L=Tokyo, S=Tokyo, C=JP"

    - name: Build App Bundle (Release - signed with upload key)
      run: flutter build appbundle --release

    - name: Build APK (Release - signed with upload key) 
      run: flutter build apk --release

    - name: Backup signed AAB
      run: |
        mkdir -p build/app/outputs/bundle/release/backup
        cp build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/backup/app-release-signed.aab

    - name: Remove keystore temporarily for unsigned build
      run: rm -f android/app/keystore.jks

    - name: Build App Bundle (Release - unsigned)
      run: flutter build appbundle --release

    - name: Rename unsigned AAB
      run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/app-release-unsigned.aab

    - name: Restore signed AAB as default
      run: cp build/app/outputs/bundle/release/backup/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab

    - name: Verify AAB files exist
      run: |
        ls -la build/app/outputs/bundle/release/
        file build/app/outputs/bundle/release/app-release.aab
        file build/app/outputs/bundle/release/app-release-unsigned.aab
        echo "Signed AAB file size: $(stat -c%s build/app/outputs/bundle/release/app-release.aab) bytes"
        echo "Unsigned AAB file size: $(stat -c%s build/app/outputs/bundle/release/app-release-unsigned.aab) bytes"

    - name: Upload Signed App Bundle for Google Play
      uses: actions/upload-artifact@v4
      with:
        name: google-play-aab-signed
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Upload Unsigned App Bundle for Google Play
      uses: actions/upload-artifact@v4
      with:
        name: google-play-aab-unsigned
        path: build/app/outputs/bundle/release/app-release-unsigned.aab
        retention-days: 30

    - name: Upload APK for testing
      uses: actions/upload-artifact@v4  
      with:
        name: testing-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

