name: Flutter CI

on:
  push:
    branches: [ main, master, develop, feature/** ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Sanity check app icons
        run: |
          ls -l android/app/src/main/res/mipmap-*/ic_launcher.png || true
          file android/app/src/main/res/mipmap-*/ic_launcher.png || true
      - name: Ensure Android SDK packages (API 35)
        run: |
          if [ -n "$ANDROID_HOME" ] && [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
            "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
              "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          else
            echo "sdkmanager not found; relying on default image SDK"
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test -r expanded
